#!/bin/bash
jupyter contrib nbextension install --user
jupyter nbextension enable init_cell/main
jupyter nbextension install --py hide_code
jupyter nbextension enable --py hide_code
jupyter serverextension enable --py hide_code
jupyter lab build
jupyter trust *.ipynb